environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37

image:
  - Visual Studio 2017

platform:
  - x86
  - x64

install:
  - "curl https://www.timeheart.net/appveyor/%PLATFORM%/libsodium-18.dll -O"
  - "curl https://www.timeheart.net/appveyor/%PLATFORM%/libnettle-6.dll -O"
  - "curl https://www.timeheart.net/appveyor/%PLATFORM%/libhogweed-4.dll -O"
  - pip install tox

build: off

test_script:
  - tox
